# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Comedy Xperiment
email: comedyxp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Comedy XPeriment is Des Moines, Iowa's Premier Improv Comedy Troupe.
  CXP has been performing improv comedy in Des Moines for over 10 years!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: comedyxp

# Build settings
markdown: kramdown
